### ISSUE TITLE
Array.includes should be on the prototype (and non-enumeratble)

### ISSUE THREAD

**Issue by esprehn** [gwmccull/react-native-polyfill#1]
This project seems to be adding a static Array.includes method (and checking for one) which doesn't exist in ES6. I think you want to use Object.defineProperty to create a non-enumerable includes method on Array.prototype.

**Comment by gwmccull** [comment]
@esprehn thanks for submitting an issue.  You're absolutely right about the mistake, thanks.

@antoinerousseau has submitted a PR to fix it and I just merged and published v1.0.1

Thanks again for using `react-native-polyfill`!
